/* ============================================================================
   services/product/mock.ts — Mock product catalog (48 SKUs)
   Source: Architecture Plan v1.1 §21.4 (mock data: 48 SKUs, real-feeling names)
   ============================================================================ */

import type { Product, ProductImage } from "./types";

function images(slug: string, category: string, mainAlt: string): ProductImage[] {
  const base = `/products/${category}/${slug}`;
  return [
    { url: `${base}/main-1200.png`, width: 1200, height: 1500, alt: `${mainAlt} — main view`, view: "main" },
    { url: `${base}/detail-1-1200.png`, width: 1200, height: 1500, alt: `${mainAlt} — detail`, view: "detail" },
    { url: `${base}/lifestyle-1-1200.png`, width: 1200, height: 1500, alt: `${mainAlt} — in a home setting`, view: "lifestyle" },
  ];
}

export const mockProducts: Product[] = [
  {
    slug: "brass-lotus-table-lamp",
    name: "Brass Lotus Table Lamp",
    category: "lamps",
    subcategory: "table-lamps",
    price: 8499,
    compareAtPrice: 9999,
    currency: "PKR",
    shortDescription: "Hand-hammered brass table lamp with a lotus-shaped base.",
    description: "Each Lotus lamp begins as a flat sheet of brass, hand-hammered over three days by a third-generation artisan in Peshawar. The lotus base is polished by hand and paired with a linen shade stitched in Karachi. Takes a standard E27 bulb. We recommend a 2700K warm-white for the intended ambience. Brass develops a natural patina over years; many of our customers consider this a feature.",
    images: images("brass-lotus-table-lamp", "lamps", "Brass Lotus Table Lamp"),
    cardImage: { url: "/products/lamps/brass-lotus-table-lamp/card-600.png", width: 600, height: 750, alt: "Brass Lotus Table Lamp" },
    inventory: { status: "in-stock", quantity: 12 },
    rating: { average: 4.8, count: 47 },
    metadata: { material: "Hand-hammered brass, linen shade", height: "48 cm", width: "28 cm", bulb: "E27, 2700K recommended", wattage: "Max 40W", weight: "2.4 kg", origin: "Peshawar, Pakistan" },
    tags: ["bestseller", "brass", "handmade"],
    featured: true,
  },
  {
    slug: "cane-weave-floor-lamp",
    name: "Cane Weave Floor Lamp",
    category: "lamps",
    subcategory: "floor-lamps",
    price: 14999,
    currency: "PKR",
    shortDescription: "Tall floor lamp with handwoven cane shade, oak stand.",
    description: "A floor lamp that does the work of a window. The handwoven cane shade diffuses the bulb into a soft, even glow. The stand is solid oak, turned in Sialkot, with a brushed brass foot. At 1.6 metres tall it sits behind a sofa or beside a reading chair.",
    images: images("cane-weave-floor-lamp", "lamps", "Cane Weave Floor Lamp"),
    cardImage: { url: "/products/lamps/cane-weave-floor-lamp/card-600.png", width: 600, height: 750, alt: "Cane Weave Floor Lamp" },
    inventory: { status: "in-stock", quantity: 6 },
    rating: { average: 4.7, count: 31 },
    metadata: { material: "Handwoven cane, solid oak, brass foot", height: "160 cm", width: "38 cm", bulb: "E27, 2700K LED", wattage: "Max 60W", weight: "4.1 kg", origin: "Sialkot, Pakistan" },
    tags: ["bestseller", "natural"],
    featured: true,
  },
  {
    slug: "ceramic-moon-table-lamp",
    name: "Ceramic Moon Table Lamp",
    category: "lamps",
    subcategory: "table-lamps",
    price: 6499,
    compareAtPrice: 7999,
    currency: "PKR",
    shortDescription: "Glazed ceramic table lamp in moon-white, cotton shade.",
    description: "Thrown on a wheel in Hala, Sindh, the Moon lamp is glazed in a soft matte white. The shade is undyed cotton. Small enough for a bedside table and quiet enough to live next to a sleeping person.",
    images: images("ceramic-moon-table-lamp", "lamps", "Ceramic Moon Table Lamp"),
    cardImage: { url: "/products/lamps/ceramic-moon-table-lamp/card-600.png", width: 600, height: 750, alt: "Ceramic Moon Table Lamp" },
    inventory: { status: "low-stock", quantity: 4 },
    rating: { average: 4.6, count: 22 },
    metadata: { material: "Glazed ceramic, cotton shade", height: "34 cm", width: "22 cm", bulb: "E14, 2700K", wattage: "Max 25W", weight: "1.6 kg", origin: "Hala, Sindh" },
    tags: ["sale", "ceramic"],
    featured: false,
  },
  {
    slug: "brass-mehrab-pendant",
    name: "Brass Mehrab Pendant Light",
    category: "lamps",
    subcategory: "pendant-lights",
    price: 18999,
    currency: "PKR",
    shortDescription: "Pendant light inspired by mehrab arches, hand-cut brass.",
    description: "The Mehrab pendant takes its silhouette from the arched niches in mosques. Hand-cut from a single sheet of brass, the arch throws a patterned shadow when lit.",
    images: images("brass-mehrab-pendant", "lamps", "Brass Mehrab Pendant Light"),
    cardImage: { url: "/products/lamps/brass-mehrab-pendant/card-600.png", width: 600, height: 750, alt: "Brass Mehrab Pendant Light" },
    inventory: { status: "in-stock", quantity: 8 },
    rating: { average: 4.9, count: 18 },
    metadata: { material: "Hand-cut brass", height: "42 cm", width: "30 cm", bulb: "E27", wattage: "Max 60W", weight: "1.8 kg", origin: "Lahore, Pakistan" },
    tags: ["pendant", "architectural"],
    featured: true,
  },
  {
    slug: "travertine-block-lamp",
    name: "Travertine Block Table Lamp",
    category: "lamps",
    subcategory: "table-lamps",
    price: 12999,
    currency: "PKR",
    shortDescription: "Solid travertine block with recessed LED strip, minimalist.",
    description: "A block of Italian travertine, cut and polished in Karachi, with a warm LED strip recessed into the top edge. The light throws upward and washes the wall behind it.",
    images: images("travertine-block-lamp", "lamps", "Travertine Block Table Lamp"),
    cardImage: { url: "/products/lamps/travertine-block-lamp/card-600.png", width: 600, height: 750, alt: "Travertine Block Table Lamp" },
    inventory: { status: "in-stock", quantity: 5 },
    rating: { average: 4.7, count: 14 },
    metadata: { material: "Italian travertine, integrated LED", height: "30 cm", width: "15 cm", bulb: "Integrated 2700K LED, 8W", wattage: "8W", weight: "5.2 kg", origin: "Karachi, Pakistan" },
    tags: ["minimal", "stone"],
    featured: false,
  },
  {
    slug: "onyx-stone-lamp",
    name: "Onyx Stone Table Lamp",
    category: "lamps",
    subcategory: "table-lamps",
    price: 16999,
    compareAtPrice: 19999,
    currency: "PKR",
    shortDescription: "Translucent Balochistan onyx that glows when lit.",
    description: "Mined in Balochistan and cut in Karachi, onyx is translucent — light passes through the stone. When you switch this lamp on, the whole block glows, revealing veins of amber and cream.",
    images: images("onyx-stone-lamp", "lamps", "Onyx Stone Table Lamp"),
    cardImage: { url: "/products/lamps/onyx-stone-lamp/card-600.png", width: 600, height: 750, alt: "Onyx Stone Table Lamp" },
    inventory: { status: "low-stock", quantity: 3 },
    rating: { average: 4.9, count: 19 },
    metadata: { material: "Balochistan onyx, brass base", height: "32 cm", width: "18 cm", bulb: "E14, 2700K", wattage: "Max 25W", weight: "3.4 kg", origin: "Balochistan" },
    tags: ["sale", "stone", "natural"],
    featured: true,
  },
  {
    slug: "linen-drum-pendant",
    name: "Linen Drum Pendant",
    category: "lamps",
    subcategory: "pendant-lights",
    price: 7999,
    currency: "PKR",
    shortDescription: "Simple drum pendant in natural linen, oak rim.",
    description: "A drum-shaped pendant with a natural linen shade and a turned oak rim. The most versatile light we make.",
    images: images("linen-drum-pendant", "lamps", "Linen Drum Pendant"),
    cardImage: { url: "/products/lamps/linen-drum-pendant/card-600.png", width: 600, height: 750, alt: "Linen Drum Pendant" },
    inventory: { status: "in-stock", quantity: 20 },
    rating: { average: 4.6, count: 41 },
    metadata: { material: "Natural linen, oak rim, brass rose", height: "22 cm", width: "40 cm", bulb: "E27", wattage: "Max 60W", weight: "1.4 kg", origin: "Karachi, Pakistan" },
    tags: ["pendant", "natural", "minimal"],
    featured: false,
  },
  {
    slug: "terracotta-pot-lamp",
    name: "Terracotta Pot Lamp",
    category: "lamps",
    subcategory: "table-lamps",
    price: 4999,
    currency: "PKR",
    shortDescription: "Unglazed terracotta base with jute shade, rustic warmth.",
    description: "A table lamp built around a terracotta pot thrown in Hala. The terracotta is left unglazed — it breathes, it ages, it develops character. The shade is hand-stitched jute.",
    images: images("terracotta-pot-lamp", "lamps", "Terracotta Pot Lamp"),
    cardImage: { url: "/products/lamps/terracotta-pot-lamp/card-600.png", width: 600, height: 750, alt: "Terracotta Pot Lamp" },
    inventory: { status: "in-stock", quantity: 18 },
    rating: { average: 4.5, count: 33 },
    metadata: { material: "Unglazed terracotta, jute shade", height: "38 cm", width: "24 cm", bulb: "E14", wattage: "Max 25W", weight: "1.9 kg", origin: "Hala, Sindh" },
    tags: ["rustic", "terracotta"],
    featured: false,
  },
  {
    slug: "brass-arc-floor-lamp",
    name: "Brass Arc Floor Lamp",
    category: "lamps",
    subcategory: "floor-lamps",
    price: 19999,
    compareAtPrice: 22999,
    currency: "PKR",
    shortDescription: "Solid brass arc floor lamp, marble base, overhead light.",
    description: "An arc of solid brass rising from a block of white marble, ending in a downward-facing shade. The arc throws light over a sofa or reading chair without needing a side table.",
    images: images("brass-arc-floor-lamp", "lamps", "Brass Arc Floor Lamp"),
    cardImage: { url: "/products/lamps/brass-arc-floor-lamp/card-600.png", width: 600, height: 750, alt: "Brass Arc Floor Lamp" },
    inventory: { status: "in-stock", quantity: 4 },
    rating: { average: 4.8, count: 16 },
    metadata: { material: "Solid brass, white marble base", height: "185 cm", width: "40 cm base", bulb: "E27", wattage: "Max 60W", weight: "12.5 kg", origin: "Karachi, Pakistan" },
    tags: ["sale", "floor-lamp", "brass"],
    featured: true,
  },
  {
    slug: "walnut-reading-lamp",
    name: "Walnut Reading Lamp",
    category: "lamps",
    subcategory: "table-lamps",
    price: 7499,
    currency: "PKR",
    shortDescription: "Adjustable walnut reading lamp, brass joint, focused beam.",
    description: "A reading lamp for people who actually read in bed. The head adjusts with a brass knuckle joint that holds its position. The walnut body is turned in Murree.",
    images: images("walnut-reading-lamp", "lamps", "Walnut Reading Lamp"),
    cardImage: { url: "/products/lamps/walnut-reading-lamp/card-600.png", width: 600, height: 750, alt: "Walnut Reading Lamp" },
    inventory: { status: "in-stock", quantity: 9 },
    rating: { average: 4.8, count: 21 },
    metadata: { material: "Solid walnut, brass joint", height: "52 cm", width: "20 cm", bulb: "E14", wattage: "Max 25W", weight: "1.8 kg", origin: "Murree, Pakistan" },
    tags: ["reading", "wood"],
    featured: false,
  },
  {
    slug: "monstera-deliciosa-medium",
    name: "Monstera Deliciosa — Medium",
    category: "plants",
    subcategory: "indoor-tropicals",
    price: 3499,
    currency: "PKR",
    shortDescription: "Mature split-leaf monstera, 80cm tall, in terracotta.",
    description: "Grown in a shaded polytunnel outside Karachi, acclimatised to indoor light over four weeks. At 80cm tall in a 25cm terracotta pot, this is a plant that makes a statement. Water when the top 2cm of soil is dry. Bright indirect light.",
    images: images("monstera-deliciosa-medium", "plants", "Monstera Deliciosa Medium"),
    cardImage: { url: "/products/plants/monstera-deliciosa-medium/card-600.png", width: 600, height: 750, alt: "Monstera Deliciosa Medium" },
    inventory: { status: "in-stock", quantity: 24 },
    rating: { average: 4.8, count: 89 },
    metadata: { species: "Monstera deliciosa", size: "80 cm tall", pot: "25 cm terracotta", light: "Bright indirect", water: "Weekly", toxicity: "Mildly toxic to pets", origin: "Grown in Karachi" },
    tags: ["bestseller", "pet-caution", "statement"],
    featured: true,
  },
  {
    slug: "snake-plant-sansevieria",
    name: "Snake Plant (Sansevieria)",
    category: "plants",
    subcategory: "low-light",
    price: 2499,
    currency: "PKR",
    shortDescription: "Nearly indestructible, air-purifying, low-light tolerant.",
    description: "The Snake Plant tolerates low light, irregular watering, and Karachi's load-shedding-driven temperature swings. NASA-rated as an air purifier. Approximately 60cm tall in a 20cm terracotta pot.",
    images: images("snake-plant-sansevieria", "plants", "Snake Plant"),
    cardImage: { url: "/products/plants/snake-plant-sansevieria/card-600.png", width: 600, height: 750, alt: "Snake Plant" },
    inventory: { status: "in-stock", quantity: 35 },
    rating: { average: 4.9, count: 124 },
    metadata: { species: "Sansevieria trifasciata", size: "60 cm tall", pot: "20 cm terracotta", light: "Low to bright indirect", water: "Every 2–3 weeks", toxicity: "Mildly toxic to pets", origin: "Grown in Karachi" },
    tags: ["bestseller", "low-light", "beginner", "air-purifying"],
    featured: true,
  },
  {
    slug: "pothos-golden-hanging",
    name: "Golden Pothos — Hanging",
    category: "plants",
    subcategory: "trailing",
    price: 1799,
    compareAtPrice: 2199,
    currency: "PKR",
    shortDescription: "Trailing vines, variegated leaves, hanging pot ready.",
    description: "The Golden Pothos is the easiest trailing plant we sell. It forgives neglect and grows quickly. Comes in a 15cm hanging pot with an integrated hook.",
    images: images("pothos-golden-hanging", "plants", "Golden Pothos"),
    cardImage: { url: "/products/plants/pothos-golden-hanging/card-600.png", width: 600, height: 750, alt: "Golden Pothos" },
    inventory: { status: "in-stock", quantity: 40 },
    rating: { average: 4.8, count: 67 },
    metadata: { species: "Epipremnum aureum", size: "40–60 cm trails", pot: "15 cm hanging pot", light: "Low to bright indirect", water: "Weekly", toxicity: "Toxic to pets", origin: "Grown in Karachi" },
    tags: ["sale", "trailing", "beginner"],
    featured: false,
  },
  {
    slug: "zz-plant-zamioculcas",
    name: "ZZ Plant (Zamioculcas)",
    category: "plants",
    subcategory: "low-light",
    price: 2999,
    currency: "PKR",
    shortDescription: "Glossy black-green leaves, drought-tolerant, office hero.",
    description: "The ZZ Plant is the plant you put in a windowless office or a dark corner, and then forget about for a month. Its waxy leaves reflect light in a way that makes a dim room look intentional.",
    images: images("zz-plant-zamioculcas", "plants", "ZZ Plant"),
    cardImage: { url: "/products/plants/zz-plant-zamioculcas/card-600.png", width: 600, height: 750, alt: "ZZ Plant" },
    inventory: { status: "in-stock", quantity: 18 },
    rating: { average: 4.7, count: 43 },
    metadata: { species: "Zamioculcas zamiifolia", size: "55 cm tall", pot: "20 cm terracotta", light: "Low to bright indirect", water: "Every 3–4 weeks", toxicity: "Toxic to pets", origin: "Grown in Karachi" },
    tags: ["low-light", "drought-tolerant"],
    featured: false,
  },
  {
    slug: "fiddle-leaf-fig-large",
    name: "Fiddle Leaf Fig — Large",
    category: "plants",
    subcategory: "statement-trees",
    price: 7999,
    compareAtPrice: 9499,
    currency: "PKR",
    shortDescription: "Statement fiddle leaf, 1.4m tall, premium grade.",
    description: "The Fiddle Leaf Fig is the diva of indoor plants — and the most photogenic. We ship only premium-grade plants acclimatised to indoor light. At 1.4 metres tall, this is a plant that defines a room.",
    images: images("fiddle-leaf-fig-large", "plants", "Fiddle Leaf Fig Large"),
    cardImage: { url: "/products/plants/fiddle-leaf-fig-large/card-600.png", width: 600, height: 750, alt: "Fiddle Leaf Fig Large" },
    inventory: { status: "low-stock", quantity: 5 },
    rating: { average: 4.5, count: 38 },
    metadata: { species: "Ficus lyrata", size: "1.4 m tall", pot: "30 cm terracotta", light: "Bright indirect", water: "Weekly", toxicity: "Toxic to pets", origin: "Grown in Karachi" },
    tags: ["sale", "statement", "statement-tree"],
    featured: true,
  },
  {
    slug: "areca-palm-medium",
    name: "Areca Palm — Medium",
    category: "plants",
    subcategory: "palms",
    price: 3999,
    currency: "PKR",
    shortDescription: "Feathery palm, air-purifying, humidifies the room.",
    description: "The Areca Palm makes a Karachi apartment feel like a hill station veranda. Its feathery fronds soften any corner, and it transpires heavily, raising humidity in air-conditioned rooms.",
    images: images("areca-palm-medium", "plants", "Areca Palm"),
    cardImage: { url: "/products/plants/areca-palm-medium/card-600.png", width: 600, height: 750, alt: "Areca Palm" },
    inventory: { status: "in-stock", quantity: 16 },
    rating: { average: 4.6, count: 52 },
    metadata: { species: "Dypsis lutescens", size: "1.2 m tall", pot: "25 cm terracotta", light: "Bright indirect", water: "Twice weekly in summer", toxicity: "Pet-safe", origin: "Grown in Karachi" },
    tags: ["palm", "air-purifying", "pet-safe"],
    featured: true,
  },
  {
    slug: "peace-lily-medium",
    name: "Peace Lily — Medium",
    category: "plants",
    subcategory: "flowering",
    price: 2799,
    currency: "PKR",
    shortDescription: "White blooms, low-light tolerant, tells you when thirsty.",
    description: "The Peace Lily communicates. Its leaves droop visibly when it needs water — you water it, and an hour later it is standing tall again. It produces elegant white blooms through the year.",
    images: images("peace-lily-medium", "plants", "Peace Lily"),
    cardImage: { url: "/products/plants/peace-lily-medium/card-600.png", width: 600, height: 750, alt: "Peace Lily" },
    inventory: { status: "in-stock", quantity: 22 },
    rating: { average: 4.7, count: 61 },
    metadata: { species: "Spathiphyllum wallisii", size: "45 cm tall", pot: "18 cm terracotta", light: "Low to bright indirect", water: "Weekly", toxicity: "Mildly toxic to pets", origin: "Grown in Karachi" },
    tags: ["flowering", "low-light"],
    featured: false,
  },
  {
    slug: "string-of-pearls",
    name: "String of Pearls",
    category: "plants",
    subcategory: "trailing",
    price: 2299,
    currency: "PKR",
    shortDescription: "Cascading pearl-like leaves, sun-loving, dramatic.",
    description: "A succulent vine whose leaves look like small green peas. Cascading from a shelf or hanging pot, it is one of the most photographed plants on the internet — and trickier than it looks.",
    images: images("string-of-pearls", "plants", "String of Pearls"),
    cardImage: { url: "/products/plants/string-of-pearls/card-600.png", width: 600, height: 750, alt: "String of Pearls" },
    inventory: { status: "low-stock", quantity: 6 },
    rating: { average: 4.4, count: 34 },
    metadata: { species: "Curio rowleyanus", size: "30–40 cm trails", pot: "15 cm hanging pot", light: "Bright direct to indirect", water: "Every 2 weeks", toxicity: "Toxic to pets", origin: "Grown in Karachi" },
    tags: ["trailing", "succulent"],
    featured: false,
  },
  {
    slug: "rubber-tree-burgundy",
    name: "Burgundy Rubber Tree",
    category: "plants",
    subcategory: "statement-trees",
    price: 4999,
    currency: "PKR",
    shortDescription: "Deep burgundy leaves, structural, easier than a fiddle.",
    description: "The Burgundy Rubber Tree has the dramatic presence of a fiddle leaf fig with none of the temperament. Its leaves are a deep, near-black burgundy that catches light like polished leather.",
    images: images("rubber-tree-burgundy", "plants", "Burgundy Rubber Tree"),
    cardImage: { url: "/products/plants/rubber-tree-burgundy/card-600.png", width: 600, height: 750, alt: "Burgundy Rubber Tree" },
    inventory: { status: "in-stock", quantity: 12 },
    rating: { average: 4.7, count: 29 },
    metadata: { species: "Ficus elastica Burgundy", size: "1 m tall", pot: "25 cm terracotta", light: "Medium to bright indirect", water: "Weekly", toxicity: "Toxic to pets", origin: "Grown in Karachi" },
    tags: ["statement", "burgundy"],
    featured: false,
  },
  {
    slug: "saffron-oud-pillar-candle",
    name: "Saffron & Oud Pillar Candle",
    category: "candles",
    subcategory: "pillar",
    price: 2499,
    currency: "PKR",
    shortDescription: "Soy wax, saffron and oud, 60-hour burn, brass vessel.",
    description: "Our signature scent. Saffron from Kashmir, blended with dark, resinous oud. Hand-poured in small batches using 100% soy wax. 60-hour burn time. Comes in a reusable brass vessel.",
    images: images("saffron-oud-pillar-candle", "candles", "Saffron & Oud Pillar Candle"),
    cardImage: { url: "/products/candles/saffron-oud-pillar-candle/card-600.png", width: 600, height: 750, alt: "Saffron & Oud Pillar Candle" },
    inventory: { status: "in-stock", quantity: 30 },
    rating: { average: 4.9, count: 142 },
    metadata: { wax: "100% soy wax", scent: "Saffron & Oud", burnTime: "60 hours", weight: "320 g", vessel: "Reusable brass", wick: "Cotton", origin: "Karachi, Pakistan" },
    tags: ["bestseller", "signature", "brass-vessel"],
    featured: true,
  },
  {
    slug: "rose-sandalwood-jar-candle",
    name: "Rose & Sandalwood Jar Candle",
    category: "candles",
    subcategory: "jar",
    price: 1999,
    currency: "PKR",
    shortDescription: "Damask rose and Mysore sandalwood, 45-hour burn, glass.",
    description: "Damask rose from Lahore, paired with creamy Mysore sandalwood. A fragrance that smells like a wedding, like a mother's dressing table, like a memory you cannot quite place.",
    images: images("rose-sandalwood-jar-candle", "candles", "Rose & Sandalwood Jar Candle"),
    cardImage: { url: "/products/candles/rose-sandalwood-jar-candle/card-600.png", width: 600, height: 750, alt: "Rose & Sandalwood Jar Candle" },
    inventory: { status: "in-stock", quantity: 26 },
    rating: { average: 4.8, count: 98 },
    metadata: { wax: "Soy and coconut blend", scent: "Rose & Sandalwood", burnTime: "45 hours", weight: "260 g", vessel: "Glass with wooden lid", wick: "Wooden", origin: "Karachi, Pakistan" },
    tags: ["bestseller", "rose", "wooden-wick"],
    featured: true,
  },
  {
    slug: "cardamom-coffee-soy-candle",
    name: "Cardamom & Coffee Soy Candle",
    category: "candles",
    subcategory: "jar",
    price: 1799,
    compareAtPrice: 2199,
    currency: "PKR",
    shortDescription: "Green cardamom and dark coffee, 40-hour burn, ceramic.",
    description: "Green cardamom — the elaichi crushed at the start of Qahwa — folded into dark roast coffee. A candle that smells like a winter morning in a Northern Areas guesthouse.",
    images: images("cardamom-coffee-soy-candle", "candles", "Cardamom & Coffee Soy Candle"),
    cardImage: { url: "/products/candles/cardamom-coffee-soy-candle/card-600.png", width: 600, height: 750, alt: "Cardamom & Coffee Soy Candle" },
    inventory: { status: "in-stock", quantity: 22 },
    rating: { average: 4.7, count: 71 },
    metadata: { wax: "100% soy wax", scent: "Cardamom & Coffee", burnTime: "40 hours", weight: "220 g", vessel: "Hand-glazed ceramic", wick: "Cotton", origin: "Karachi & Hala" },
    tags: ["sale", "ceramic-vessel", "coffee"],
    featured: false,
  },
  {
    slug: "jasmine-night-bloom-candle",
    name: "Jasmine Night Bloom Candle",
    category: "candles",
    subcategory: "jar",
    price: 2199,
    currency: "PKR",
    shortDescription: "Night-blooming jasmine (raat ki rani), 50-hour burn.",
    description: "Raat ki rani — the night-blooming jasmine that perfumes Karachi's gardens after sunset. Sweet, heady, and unmistakably nighttime. 50-hour burn in frosted glass.",
    images: images("jasmine-night-bloom-candle", "candles", "Jasmine Night Bloom Candle"),
    cardImage: { url: "/products/candles/jasmine-night-bloom-candle/card-600.png", width: 600, height: 750, alt: "Jasmine Night Bloom Candle" },
    inventory: { status: "in-stock", quantity: 19 },
    rating: { average: 4.8, count: 64 },
    metadata: { wax: "100% soy wax", scent: "Night-blooming Jasmine", burnTime: "50 hours", weight: "280 g", vessel: "Frosted glass", wick: "Cotton", origin: "Karachi, Pakistan" },
    tags: ["jasmine", "night-bloom"],
    featured: true,
  },
  {
    slug: "mogra-jasmine-candle",
    name: "Mogra Jasmine Candle",
    category: "candles",
    subcategory: "jar",
    price: 2299,
    currency: "PKR",
    shortDescription: "Pure mogra (Arabian jasmine), sweet and heady, 45-hour.",
    description: "Mogra — the Arabian jasmine strung into garlands at every Pakistani wedding. Extracted from flowers grown outside Lahore. The candle smells exactly like the garland.",
    images: images("mogra-jasmine-candle", "candles", "Mogra Jasmine Candle"),
    cardImage: { url: "/products/candles/mogra-jasmine-candle/card-600.png", width: 600, height: 750, alt: "Mogra Jasmine Candle" },
    inventory: { status: "in-stock", quantity: 21 },
    rating: { average: 4.9, count: 87 },
    metadata: { wax: "100% soy wax", scent: "Mogra (Arabian Jasmine)", burnTime: "45 hours", weight: "260 g", vessel: "Glass jar", wick: "Cotton", origin: "Lahore & Karachi" },
    tags: ["mogra", "wedding", "bestseller"],
    featured: true,
  },
  {
    slug: "oud-amber-pillar-candle",
    name: "Oud & Amber Pillar Candle",
    category: "candles",
    subcategory: "pillar",
    price: 2899,
    currency: "PKR",
    shortDescription: "Oud, amber, vanilla. Deep and resinous, 60-hour, brass.",
    description: "Our deepest candle. Oud layered over warm amber and a base of vanilla. The candle you light when the guests have gone home. 60-hour burn in a reusable brass vessel.",
    images: images("oud-amber-pillar-candle", "candles", "Oud & Amber Pillar Candle"),
    cardImage: { url: "/products/candles/oud-amber-pillar-candle/card-600.png", width: 600, height: 750, alt: "Oud & Amber Pillar Candle" },
    inventory: { status: "in-stock", quantity: 12 },
    rating: { average: 4.9, count: 58 },
    metadata: { wax: "100% soy wax", scent: "Oud, Amber & Vanilla", burnTime: "60 hours", weight: "340 g", vessel: "Reusable brass", wick: "Cotton", origin: "Karachi, Pakistan" },
    tags: ["deep", "brass-vessel", "oud"],
    featured: true,
  },
  {
    slug: "white-musk-candle",
    name: "White Musk Candle",
    category: "candles",
    subcategory: "jar",
    price: 2199,
    currency: "PKR",
    shortDescription: "Clean white musk, soft and powdery, 45-hour.",
    description: "A candle for people who do not want to smell a candle. White musk — clean, soft, a little powdery. It just makes the room feel like clean laundry and quiet.",
    images: images("white-musk-candle", "candles", "White Musk Candle"),
    cardImage: { url: "/products/candles/white-musk-candle/card-600.png", width: 600, height: 750, alt: "White Musk Candle" },
    inventory: { status: "in-stock", quantity: 17 },
    rating: { average: 4.6, count: 33 },
    metadata: { wax: "100% soy wax", scent: "White Musk", burnTime: "45 hours", weight: "260 g", vessel: "Frosted glass", wick: "Cotton", origin: "Karachi, Pakistan" },
    tags: ["musk", "subtle", "gift"],
    featured: false,
  },
  {
    slug: "pomegranate-rose-candle",
    name: "Pomegranate & Rose Candle",
    category: "candles",
    subcategory: "seasonal",
    price: 2399,
    compareAtPrice: 2799,
    currency: "PKR",
    shortDescription: "Pomegranate and red rose, festive, 45-hour, ceramic.",
    description: "Pomegranate — the anar that signals winter in Pakistan — paired with red rose. A festive candle we pour from October to February. 45-hour burn in hand-glazed ceramic.",
    images: images("pomegranate-rose-candle", "candles", "Pomegranate & Rose Candle"),
    cardImage: { url: "/products/candles/pomegranate-rose-candle/card-600.png", width: 600, height: 750, alt: "Pomegranate & Rose Candle" },
    inventory: { status: "low-stock", quantity: 4 },
    rating: { average: 4.8, count: 22 },
    metadata: { wax: "100% soy wax", scent: "Pomegranate & Rose", burnTime: "45 hours", weight: "260 g", vessel: "Hand-glazed ceramic", wick: "Cotton", origin: "Karachi & Hala" },
    tags: ["sale", "seasonal", "festive"],
    featured: false,
  },
  {
    slug: "unscented-beeswax-tapers",
    name: "Unscented Beeswax Tapers (Pair)",
    category: "candles",
    subcategory: "tapers",
    price: 899,
    currency: "PKR",
    shortDescription: "Pure beeswax tapers, pair, 8-hour dripless burn.",
    description: "A pair of pure beeswax tapers, hand-dipped in Chakwal. Unscented — for the dinner table. 8-hour burn each. 25cm tall, fits standard taper holders.",
    images: images("unscented-beeswax-tapers", "candles", "Unscented Beeswax Tapers"),
    cardImage: { url: "/products/candles/unscented-beeswax-tapers/card-600.png", width: 600, height: 750, alt: "Unscented Beeswax Tapers" },
    inventory: { status: "in-stock", quantity: 38 },
    rating: { average: 4.7, count: 54 },
    metadata: { wax: "100% beeswax", scent: "Unscented", burnTime: "8 hours each", weight: "70 g each", vessel: "None", wick: "Cotton", origin: "Chakwal, Pakistan" },
    tags: ["tapers", "beeswax", "dinner"],
    featured: false,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return mockProducts.filter((p) => p.category === category);
}

export function getFeaturedProducts(limit = 8): Product[] {
  return mockProducts.filter((p) => p.featured).slice(0, limit);
}

export function getBestsellers(limit = 8): Product[] {
  return mockProducts
    .filter((p) => p.tags.includes("bestseller"))
    .sort((a, b) => (b.rating?.count ?? 0) - (a.rating?.count ?? 0))
    .slice(0, limit);
}

export function getRelatedProducts(slug: string, limit = 6): Product[] {
  const product = getProductBySlug(slug);
  if (!product) return [];
  return mockProducts
    .filter((p) => p.category === product.category && p.slug !== slug)
    .slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return mockProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.shortDescription.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q)) ||
      p.category.toLowerCase().includes(q)
  );
}

export function getAllProducts(): Product[] {
  return mockProducts;
}
